//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersPhotoUpload.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\mscs-fs-01\\PhotoDB\\")]
        public string FolderRoot {
            get {
                return ((string)(this["FolderRoot"]));
            }
            set {
                this["FolderRoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Казань")]
        public string FolderKzkk {
            get {
                return ((string)(this["FolderKzkk"]));
            }
            set {
                this["FolderKzkk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Краснодар")]
        public string FolderKdtt {
            get {
                return ((string)(this["FolderKdtt"]));
            }
            set {
                this["FolderKdtt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Москва")]
        public string FolderMssu {
            get {
                return ((string)(this["FolderMssu"]));
            }
            set {
                this["FolderMssu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Москва")]
        public string FolderMspo {
            get {
                return ((string)(this["FolderMspo"]));
            }
            set {
                this["FolderMspo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Москва")]
        public string FolderMskm {
            get {
                return ((string)(this["FolderMskm"]));
            }
            set {
                this["FolderMskm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Санкт-Петербург")]
        public string FolderSplp {
            get {
                return ((string)(this["FolderSplp"]));
            }
            set {
                this["FolderSplp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Сочи")]
        public string FolderSctrk {
            get {
                return ((string)(this["FolderSctrk"]));
            }
            set {
                this["FolderSctrk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("УК")]
        public string FolderMskv {
            get {
                return ((string)(this["FolderMskv"]));
            }
            set {
                this["FolderMskv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Уфа")]
        public string FolderUfkk {
            get {
                return ((string)(this["FolderUfkk"]));
            }
            set {
                this["FolderUfkk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Каменск-Уральский")]
        public string FolderYekuk {
            get {
                return ((string)(this["FolderYekuk"]));
            }
            set {
                this["FolderYekuk"] = value;
            }
        }
    }
}
